[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shadow_swap = "DcCs5AEhd6Sx5opAjhkpNUtNSQwQf7GV3UU7JsfxcvXu"

[programs.devnet]
shadow_swap = "D1gSf58XLm4VN5BqLai5d21fQngz4D7GWXZDPKieW7K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
setup = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"scripts/setup-devnet.ts\""
clear = "node scripts/clear-orders.js"
