[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shadow_swap = "CwE5KHSTsStjt2pBYjK7G7vH5T1dk3tBvePb1eg26uhA"

[programs.devnet]
shadow_swap = "CwE5KHSTsStjt2pBYjK7G7vH5T1dk3tBvePb1eg26uhA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
setup = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"scripts/setup-devnet.ts\""
clear = "node scripts/clear-orders.js"
